version: "3.9"
services:
  postgres:
    image: postgres:16.0
    container_name: postgres_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: wallet
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
